# Generated by Django 6.0.3 on 2026-03-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('motherboard', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('monitor', models.CharField(max_length=100)),
                ('keyboard', models.CharField(max_length=100)),
                ('mouse', models.CharField(max_length=100)),
            ],
        ),
    ]
